baseURL: "/"
languageCode: "en-us"
title: "Guilherme Fahur Bottino"
theme: "PaperMod"

pagination:
  pagerSize: 5

params:
  assets:
    css: "css/extra.css"
    favicon: "img/favicon.svg"
  env: production
  description: "Computational Biologist 路 Data Scientist 路 Educator"
  author: "Guilherme Fahur Bottino"
  defaultTheme: auto
  disableThemeToggle: false
  profileMode:
    enabled: true
    title: "Guilherme Fahur Bottino"
    subtitle: "Computational Biologist 路 Data Scientist 路 Educator"
    imageUrl: "img/headshot.jpg"
    imageTitle: "Profile"
    buttons:
      - name: About
        url: "/about/"
      - name: Research
        url: "/research/"
      - name: Teaching
        url: "/teaching/"
      - name: Publications
        url: "/publications/"

  socialIcons:
    - name: github
      url: "https://github.com/Hugemiler"
    - name: orcid
      url: "https://orcid.org/0000-0003-1953-1576"
    - name: linkedin
      url: "https://www.linkedin.com/in/guilherme-fahur-bottino-17a3709b/"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=-o1LscoAAAAJ&hl=en"
    - name: bluesky
      url: "https://bsky.app/profile/gfahurbottino.bsky.social"
    - name: email
      url: "mailto:gz101@wellesley.edu"
    - name: cv
      url: "doc/Academic_CV_Bottino.pdf"
menu:
  main:
    - name: About
      url: "/about/"
      weight: 10
    - name: Research
      url: "/research/"
      weight: 20
    - name: Teaching
      url: "/teaching/"
      weight: 30
    - name: Publications
      url: "/publications/"
      weight: 40
    - name: CV
      url: "doc/Academic_CV_Bottino.pdf"
      weight: 50